variable "instance_size" {}
variable "key_name" {}
variable "s3_app_sg" {}
variable "db_app_sg" {}
variable "iam_instance_profile" {}
variable "s3_app_user_data" {}
variable "db_app_user_data" {}
variable "no_of_bastions" {}
variable "no_of_db_apps" {}
variable "no_of_s3_apps" {}
variable "db_app_dependency" {}
variable "public_subnets" {}
variable "private_subnets" {}
variable "bastion_sg" {}
variable "s3_tg_arn" {}
variable "db_tg_arn" {}
variable "owner" {}
