name: 'ci-terraform-plan'

on:
  push:
    branches:
      - '*'

jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - name: 'Checkout main'
      uses: actions/checkout@v3
      with:
        ref: 'main'
        fetch-depth: '1'
    - name: 'Config Terraform plugin cache'
      run: |
        echo 'plugin_cache_dir="$HOME/.terraform.d/plugin-cache"' >~/.terraformrc
        mkdir --parents ~/.terraform.d/plugin-cache
    - name: 'cat ~/.terraformrc'
      run: |
        cat ~/.terraformrc
    - name: 'Echo & ls "$HOME/.terraform.d/plugin-cache"'
      run: |
        echo "$HOME/.terraform.d/plugin-cache"
        ls "$HOME/.terraform.d/plugin-cache"
    - name: 'Cache Terraform'
      uses: actions/cache@v3
      with:
        path: |
          ~/.terraform.d/plugin-cache
        key: ${{ runner.os }}-terraform-${{ hashFiles('terraform/providers.tf') }}
    - name: 'Run terraform plan'
      timeout-minutes: 20
      env:
        TFSTATE_BUCKET: ${{ secrets.StateBucket }}
        TFSTATE_KEY: ${{ secrets.StateKey }}
        TFSTATE_REGION: ${{ vars.Region }}
        TF_VAR_owner: ${{ secrets.Owner }}
        TF_VAR_db_name: ${{ secrets.DatabaseName }}
        TF_VAR_db_user: ${{ secrets.DatabaseUser }}
        TF_VAR_db_password: ${{ secrets.DatabasePassword }}
        TF_VAR_public_key: ${{ secrets.PublicKey }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AwsAccessKeyId }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AwsSecretAccessKey }}
        AWS_DEFAULT_REGION: ${{ vars.Region }}
        AWS_DEFAULT_OUTPUT: 'json'
      run: |
        ./ci-terraform-plan.sh
    - name: 'Echo & ls "$HOME/.terraform.d/plugin-cache"'
      run: |
        echo "$HOME/.terraform.d/plugin-cache"
        ls "$HOME/.terraform.d/plugin-cache"