name: 'terraform-destroy'

on:
  workflow_dispatch:

jobs:
  terraform-destroy-aws-from-main:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v3
      with:
        ref: 'main'
        fetch-depth: '1'
    - name: 'Run terraform destroy'
      timeout-minutes: 20
      env:
        TFSTATE_BUCKET: ${{ secrets.StateBucket }}
        TFSTATE_KEY: ${{ secrets.StateKey }}
        TFSTATE_REGION: ${{ secrets.Region }}
        TF_VAR_owner: ${{ secrets.Owner }}
        TF_VAR_db_name: ${{ secrets.DatabaseName }}
        TF_VAR_db_user: ${{ secrets.DatabaseUser }}
        TF_VAR_db_password: ${{ secrets.DatabasePassword }}
        TF_VAR_public_key: ${{ secrets.PublicKey }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AwsAccessKeyId }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AwsSecretAccessKey }}
        AWS_DEFAULT_REGION: 'us-west-2'
        AWS_DEFAULT_OUTPUT: 'json'
      run: |
        ./ci-terraform-destroy.sh