name: 'terraform-destroy'

on:
  workflow_dispatch:

jobs:
  terraform-destroy-aws-from-main:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - name: 'Checkout main'
      uses: actions/checkout@v3
      with:
        ref: 'main'
        fetch-depth: '1'
    - name: 'Set up Terraform Caching'
      run: |
        mkdir -p ~/.terraform.d/plugin-cache && export TF_PLUGIN_CACHE_DIR="$HOME/.terraform.d/plugin-cache"
    - name: 'Cache Terraform'
      uses: actions/cache@v3
      with:
        path: |
          ~/.terraform.d/plugin-cache
          ~/.terraform.lock.hcl
        key: ${{ runner.os }}-terraform-${{ hashFiles('**/.provider.tf') }}
        restore-keys: |
          ${{ runner.os }}-terraform-
    - name: 'Run terraform destroy'
      timeout-minutes: 20
      env:
        TFSTATE_BUCKET: ${{ secrets.StateBucket }}
        TFSTATE_KEY: ${{ secrets.StateKey }}
        TFSTATE_REGION: ${{ vars.Region }}
        TF_VAR_owner: ${{ secrets.Owner }}
        TF_VAR_db_name: ${{ secrets.DatabaseName }}
        TF_VAR_db_user: ${{ secrets.DatabaseUser }}
        TF_VAR_db_password: ${{ secrets.DatabasePassword }}
        TF_VAR_public_key: ${{ secrets.PublicKey }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AwsAccessKeyId }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AwsSecretAccessKey }}
        AWS_DEFAULT_REGION: ${{ vars.Region }}
        AWS_DEFAULT_OUTPUT: 'json'
      run: |
        ./ci-terraform-destroy.sh